name: FastAPI SaaS CI/CD Pipeline

on:
  push:
    branches: [main, develop]

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      stack-name: FastAPIEC2Stack-Staging
      environment: staging
    secrets: inherit
    
  deploy-production:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      stack-name: FastAPIEC2Stack-Production
      environment: production
    secrets: inherit