name: PR Review Checks

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies and static analysis tools
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Code formatting check with Black
      run: black --check app/
    
    - name: Import sorting check with isort
      run: isort --check-only app/
    
    - name: Linting with flake8
      run: flake8 app/
    
    - name: Type checking with mypy
      run: mypy app/
    
    - name: Security audit with bandit
      run: bandit -r app/ -f json -o bandit-report.json && cat bandit-report.json
      continue-on-error: true
    
    - name: Dependency vulnerability check with safety
      run: safety check --json --output safety-report.json && cat safety-report.json
      continue-on-error: true
    
    - name: Upload analysis artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: static-analysis-report
        path: |
          bandit-report.json
          safety-report.json

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run unit tests in parallel
      run: |
        pytest tests/ -m "unit or not integration" \
          --cov=app \
          --cov-branch \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:unit-coverage.xml \
          --html=unit-report.html --self-contained-html \
          --junitxml=unit-results.xml \
          -n auto
    
    - name: Upload unit test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-test-results
        path: |
          unit-coverage.xml
          unit-results.xml
          unit-report.html
    
    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: unit-results.xml
        check_name: Unit Test Results

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run integration tests
      run: |
        pytest tests/ -m "integration" \
          --cov=app \
          --cov-branch \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml:integration-coverage.xml \
          --html=integration-report.html --self-contained-html \
          --junitxml=integration-results.xml
    
    - name: Upload integration test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results
        path: |
          integration-coverage.xml
          integration-results.xml
          integration-report.html
    
    - name: Publish integration test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: integration-results.xml
        check_name: Integration Test Results

  build-validation:
    name: Build Validation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Validate app structure and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
    
    - name: Validate FastAPI app can start
      run: |
        timeout 30 uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
        curl -f http://localhost:8000/health || exit 1
        pkill -f uvicorn
    
    - name: Validate CDK synthesis
      run: |
        cd infra
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install -g aws-cdk
        export REPOSITORY_URL=${{ github.server_url }}/${{ github.repository }}.git
        cdk synth FastAPIEC2Stack-Staging
        cdk synth FastAPIEC2Stack-Production

